### ISSUE TITLE
Question about one of your gists

### ISSUE THREAD

**Issue by empath** [mattdsteele/steele.blue#15]
Sorry to leave an issue about this, but I don't have a twitter account to message you directly -- I found your gist about the paprika api--- did you happen to figure out a way to update anything with the api (in particular, adding something to the grocery list)?  I tried a post request to 'groceries' and that didn't seem to work...

**Comment by mattdsteele** [comment]
Hey, thanks for the question!

No, I haven't done much with the API beyond just playing around with some `GET`s to see what it was pulling down. I only figured that part out by using [Charles Proxy](https://www.charlesproxy.com/) against my Android app to see what endpoints were being hit. I'll bet you could do the same with the Groceries list and get data back; see what's getting sent out.

I'll add it to my to-do list, but if you end up doing any further investigation with this feel free to [comment on the gist with your findings](https://gist.github.com/mattdsteele/7386ec363badfdeaad05a418b9a1f30a). Maybe if we get far enough it can become a legit repo! 😄

**Comment by mattdsteele** [comment]
@empath I found out a few things and [commented on the gist](https://gist.github.com/mattdsteele/7386ec363badfdeaad05a418b9a1f30a), hope it helps!

**Comment by empath** [comment]
Neat, thanks. Exactly what I was looking for. I'm trying to add an Alexa
skill to add stuff to the grocery list :)

**Comment by mattdsteele** [comment]
@empath Fancy! If you have anything to share let me know; I'm looking for a new side project 🚧

**Comment by mattdsteele** [comment]
@empath So I just picked up an Echo - did you happen to get the Alexa skill working? 😀
